# files=`cat files.csv`
SOURCEDIR := source
SOURCES := $(shell find $(SOURCEDIR) -name '*.yaml')
OUTDIR := dist

$(OUTDIR)/index.yaml : $(SOURCES)
	>$(OUTDIR)/index.yaml
	echo "# PreQL Standard Types Library" >> $(OUTDIR)/index.yaml
	echo "# Copyright (c) Jonathan M. Wilbur 2019. Released under an MIT License." >> $(OUTDIR)/index.yaml
	echo "# Do not edit this file. Modify files in ./source, then run 'make' instead." >> $(OUTDIR)/index.yaml
	cat $(SOURCES) >> $(OUTDIR)/index.yaml
